[[main]]
  name="Blog"
  pageRef="/blog/"
  weight=10

[[main]]
  name="About"
  pageRef="/about"
  weight=10


[[main]]
  name = "Tags"
  pageRef = "/tags"
  weight = 20

[[social]]
  name = "LinkedIn"
  pre = "fab linkedin"
  url = "https://www.linkedin.com/in/paolo-f-bongiovanni/"
  weight = 10

[[social]]
  name = "X"
  pre = "fab twitter"
  url = "https://twitter.com/ilbongione"
  weight = 10
